kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack
        # Send severity=High alerts to slack.
          match:
            severity: High
          group_wait: 10s
          repeat_interval: 1m
 
    receivers:
     - name: alert-emailer
       email_configs:
       - to: ekene.mba10@gmail.com
         send_resolved: false
         from: from-email@email.com
         smarthost: smtp.eample.com:25
         require_tls: false
    - name: slack
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#alertmanager-alerts'