apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata: 
  name: prom-graf-cluster
  region: us-east-2
nodeGroups:
  - name: grafana-ng
    desiredCapacity: 2
    instanceType: t2.medium
    ssh:
      publicKeyName: prom-graf-ue2
